title: Johnny Pan
author: Johnny Pan
email: contact@johnnypan.me
description: > # this means to ignore newlines until baseurl
  Personal blog where I share my experiences

baseurl: ""
url: /

markdown: kramdown
highlighter: rouge

plugins:
 - jekyll-seo-tag